### ISSUE TITLE
error: variable 'supp_size' set but not used

### ISSUE THREAD

**Issue by donly** [ssut/ffmpeg-on-apple-silicon#10]
```
hb-subset-cff1.cc:405:33: error: variable 'supp_size' set but not used [-Werror,-Wunused-but-set-variable]
    unsigned int  size0, size1, supp_size;
                                ^
1 error generated.
make[4]: *** [libharfbuzz_subset_la-hb-subset-cff1.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

```

**Comment by hantmac** [comment]
+1

**Comment by DevForrestWang** [comment]
CXX      libharfbuzz_subset_la-hb-subset-cff2.lo
  CXX      libharfbuzz_subset_la-hb-subset-input.lo
hb-subset-cff1.cc:405:33: error: variable 'supp_size' set but not used [-Werror,-Wunused-but-set-variable]
    unsigned int  size0, size1, supp_size;
                                ^
  CXX      libharfbuzz_subset_la-hb-subset-plan.lo
1 error generated.
make[4]: *** [libharfbuzz_subset_la-hb-subset-cff1.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1

**Comment by AsheyXD** [comment]
Same here

**Comment by minyang** [comment]
For those who experience this build issue, the following patch seems to work for me (bumping up harfbuzz from 2.7.2 to 2.7.4):

```
diff --git a/build.bash b/build.bash
index e352d0f..981a52e 100755
--- a/build.bash
+++ b/build.bash
@@ -111,8 +111,8 @@ echo "Downloading: libvorbis (1.3.7)"
 {(curl -Ls -o - https://ftp.osuosl.org/pub/xiph/releases/vorbis/libvorbis-1.3.7.tar.gz | tar zxf - -C $CMPLD/) &};
 echo "Downloading: libopus (1.3.1)"
 {(curl -Ls -o - https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz | tar zxf - -C $CMPLD/) &};
-echo "Downloading: harfbuzz (2.7.2)"
-{(curl -Ls -o - https://github.com/harfbuzz/harfbuzz/releases/download/2.7.2/harfbuzz-2.7.2.tar.xz | tar Jxf - -C $CMPLD/) &};
+echo "Downloading: harfbuzz (2.7.4)"
+{(curl -Ls -o - https://github.com/harfbuzz/harfbuzz/releases/download/2.7.4/harfbuzz-2.7.4.tar.xz | tar Jxf - -C $CMPLD/) &};
 echo "Downloading: libogg (1.3.4)"
 curl -Ls -o - https://ftp.osuosl.org/pub/xiph/releases/ogg/libogg-1.3.4.tar.gz | tar zxf - -C $CMPLD/
 curl -s -o "$CMPLD/libogg-1.3.4/fix_unsigned_typedefs.patch" "https://github.com/xiph/ogg/commit/c8fca6b4a02d695b1ceea39b330d4406001c03ed.patch?full_index=1"
@@ -341,7 +341,7 @@ function build_harfbuzz () {
   if [[ ! -e "${SRC}/lib/pkgconfig/harfbuzz.pc" ]]; then
     echo '♻️ ' Start compiling harfbuzz
     cd ${CMPLD}
-    cd harfbuzz-2.7.2
+    cd harfbuzz-2.7.4
     ./configure --prefix=${SRC} --disable-shared --enable-static
     make -j ${NUM_PARALLEL_BUILDS}
     make install
```

**Comment by dav01it** [comment]
You have to edit hb-subset-cff1.cc
remove all the three references to  the variable supp_size
It's true what the compiler says: the var is unuseful: declared, set to 0 then set to another value but never used for computational purposes.
Another solution would be to leave it and remove the "-Wunused-but-set-variable" flag to ignore it but we are compiling to have optimized code isn't it?
[hb-subset-cff1.cc.txt](https://github.com/ssut/ffmpeg-on-apple-silicon/files/9741368/hb-subset-cff1.cc.txt)

**Comment by SelimEmre** [comment]
+1 same

**Comment by marcemq** [comment]
I have the same error u.u

**Comment by nick-scott** [comment]
If you want a copy paste, here is a quick and dirty patch to get you going. (replace in `build.bash`)
```
function build_harfbuzz () {
  if [[ ! -e "${SRC}/lib/pkgconfig/harfbuzz.pc" ]]; then
    echo '♻️ ' Start compiling harfbuzz
    cd ${CMPLD}
    cd harfbuzz-2.7.2
    sed -i -e 's/unsigned int  size0, size1, supp_size;/unsigned int  size0, size1;/g' ./src/hb-subset-cff1.cc
    sed -i -e 's/supp_size = 0;//g' ./src/hb-subset-cff1.cc
    sed -i -e 's/supp_size += SuppEncoding::static_size \* supp_codes.length;//g' ./src/hb-subset-cff1.cc
    ./configure --prefix=${SRC} --disable-shared --enable-static
    make -j ${NUM_PARALLEL_BUILDS}
    make install
  fi
}
```

**Comment by utk787** [comment]
> If you want a copy paste, here is a quick and dirty patch to get you going. (replace in `build.bash`)
> 
> ```
> function build_harfbuzz () {
>   if [[ ! -e "${SRC}/lib/pkgconfig/harfbuzz.pc" ]]; then
>     echo '♻️ ' Start compiling harfbuzz
>     cd ${CMPLD}
>     cd harfbuzz-2.7.2
>     sed -i -e 's/unsigned int  size0, size1, supp_size;/unsigned int  size0, size1;/g' ./src/hb-subset-cff1.cc
>     sed -i -e 's/supp_size = 0;//g' ./src/hb-subset-cff1.cc
>     sed -i -e 's/supp_size += SuppEncoding::static_size \* supp_codes.length;//g' ./src/hb-subset-cff1.cc
>     ./configure --prefix=${SRC} --disable-shared --enable-static
>     make -j ${NUM_PARALLEL_BUILDS}
>     make install
>   fi
> }
> ```

Thanks for the suggestion, saved hours for me.
